#### general settings
name: DBSRx4_setting2
use_tb_logger: true
model: blind
distortion: sr
scale: 4
gpu_ids: [0,1,2]
pca_matrix_path: ../../../pca_matrix/DBSR/pca_aniso_matrix_x4.pth

degradation:
  random_kernel: True
  ksize: 31
  code_length: 10
  sig_min: 0.6
  sig_max: 5
  rate_iso: 0
  random_disturb: true

#### datasets
datasets:
  train:
    name: Chikusei_4blur2 #Har_blur2
    mode: GT
    dataroot_GT: /home/lwd/Dataset_yp/HSISR/Chikusei/4/Chikusei_x4_blur2/trains/

    use_shuffle: true
    n_workers: 8  # per GPU
    batch_size: 64
    GT_size: 64
    LR_size: 16
    use_flip: true
    use_rot: true
    color: RGB
    
  val:
    name: Cave#Har_blur2
    mode: LQGT
    dataroot_LQGT: /home/lwd/Dataset_yp/HSISR/Chikusei/4/Chikusei_x4_blur2/tests/

    

#### network structures
network_G:
  which_model_G: DBSR
  setting:
    nf: 64
    nb: 5 #5
    ng: 3  #3
    input_para: 256
    kernel_size: 31
    in_nc: 128 #????????,?3???31
    n_subs: 8 # the sub band in each group
    n_ovls: 2 # the number of overlap
    n_SSB_blocks: 3
    final_feats: 64
    ker_ex_numblock: 3
#### path
path:
  pretrain_model_G: ~
  strict_load: true
  resume_state: ~
  
#### training settings: learning rate scheme, loss
train:
  lr_G: !!float 5e-4
  lr_E: !!float 5e-4
  lr_scheme: MultiStepLR # CosineAnnealingLR_Restart
  beta1: 0.9 
  beta2: 0.99
  niter: 50000  
  warmup_iter: -1  # no warm up
  lr_steps: [10000,20000,30000,40000,50000]
  lr_gamma: 0.5
  eta_min: !!float 1e-7 

  pixel_criterion: myloss #l_pix.type: l1   # sam loss??? 0.1 0.05 0.01 ???,???loss?0.01????
  pixel_weight: 1.0

  manual_seed: 0
  val_freq: !!float 2500

#### logger
logger:
  print_freq: 20
  save_checkpoint_freq: !!float 2500