#### general settings
name: DBSRx8_setting2
use_tb_logger: true
model: blind
distortion: sr
scale: 8
gpu_ids: [2,3]
pca_matrix_path: ../../../pca_matrix/DBSR/pca_aniso_matrix_x4.pth

degradation:
  random_kernel: True
  ksize: 31
  code_length: 10
  sig_min: 0.6
  sig_max: 5
  rate_iso: 0
  random_disturb: true

#### datasets
datasets:
  train:
    name: Chikusei_8blur2
    mode: GT
    #dataroot_GT: /data/yp/HSI/Data/Cave/Train/4_blur/
    #dataroot_GT: /data/yp/HSI/Data/Harvard/Train/4_blur/
    dataroot_GT: /home/lwd/Dataset_yp/HSISR/Chikusei/8/Chikusei_x8_blur2/trains_large/

    use_shuffle: true
    n_workers: 8  # per GPU
    batch_size: 32
    GT_size: 128
    LR_size: 16
    use_flip: true
    use_rot: true
    color: RGB
  val:
    name: Chikusei_8blur2
    mode: LQGT
    #dataroot_LQGT: /data/yp/HSI/Data/Cave/Test/4_blur/
    #dataroot_LQGT: /data/yp/HSI/Data/Harvard/Test/4_blur/
    dataroot_LQGT: /home/lwd/Dataset_yp/HSISR/Chikusei/8/Chikusei_x8_blur2/tests/

#### network structures
network_G:
  which_model_G: DBSR
  setting:
    nf: 64
    nb: 5 #10
    ng: 3  #5
    input_para: 256
    kernel_size: 21
    in_nc: 128 #????????,?3???31
    n_subs: 8 # the sub band in each group
    n_ovls: 2 # the number of overlap
    n_SSB_blocks: 3
    final_feats: 128
    ker_ex_numblock: 3
#### path
path:
  pretrain_model_G: /home/lwd/code_yp/DBSR-SR/experiments/DBSR/DBSRx4_setting2/models/6000_G.pth
  strict_load: true
  resume_state: /home/lwd/code_yp/DBSR-SR/experiments/DBSR/DBSRx4_setting2/training_state/6000.state

#### training settings: learning rate scheme, loss
train:
  lr_G: !!float 4e-4
  lr_E: !!float 4e-4
  lr_scheme: MultiStepLR # CosineAnnealingLR_Restart
  beta1: 0.9 #adam?????
  beta2: 0.99
  niter: 30000  # 500000
  warmup_iter: -1  # no warm up
  lr_steps: [5000,10000,15000,20000,25000,30000]
  # lr_steps: [5000, 10000,15000,20000,25000,30000,35000,40000,45000]
  lr_gamma: 0.8
  eta_min: !!float 1e-7  #??????,??eta_min??????????
  #T_period: [2500, 2500,2500,2500,2500,2500]
  #restarts: [2500, 5000,7500,10000,12500]
  #restart_weights: [1, 1,1,1,1]
  pixel_criterion: myloss #l_pix.type: l1   # sam loss??? 0.1 0.05 0.01 ???,???loss?0.01????
  pixel_weight: 1.0

  manual_seed: 0
  val_freq: !!float 1000

#### logger
logger:
  print_freq: 20
  save_checkpoint_freq: !!float 1000