#### general settings
name: DBSRx4_setting1
use_tb_logger: true
model: blind
distortion: sr
scale: 4
gpu_ids: [0,1]
pca_matrix_path: ../../../pca_matrix/DBSR/pca_matrix.pth

degradation:
  random_kernel: True
  ksize: 21
  code_length: 10
  sig_min: 0.2
  sig_max: 4.0
  rate_iso: 1.0
  random_disturb: false

#### datasets
datasets:
  train:
    name: Chikusei_4blur1
    mode: GT
    #dataroot_GT: /data/yp/HSI/Data/Cave/Train/4_blur/
    #dataroot_GT: /data/yp/HSI/Data/Harvard/Train/4_blur/
    dataroot_GT: /home/lwd/Dataset_yp/HSISR/Chikusei/4/Chikusei_x4_blur/trains/


    use_shuffle: true
    n_workers: 8  # per GPU
    batch_size: 64
    GT_size: 64
    LR_size: 16
    use_flip: true
    use_rot: true
    color: RGB

  val:
    name: Chikusei_4blur1
    mode: LQGT
    #dataroot_LQGT: /data/yp/HSI/Data/Cave/Test/4_blur/
    #dataroot_LQGT: /data/yp/HSI/Data/Harvard/Test/4_blur/
    dataroot_LQGT: /home/lwd/Dataset_yp/HSISR/Chikusei/4/Chikusei_x4_blur/tests/


#### network structures
network_G:
  which_model_G: DBSR
  setting:
    nf: 64
    nb: 5 #10
    ng: 3  #5
    input_para: 256
    kernel_size: 21
    in_nc: 128 #????????,?3???31
    n_subs: 8 # the sub band in each group
    n_ovls: 2 # the number of overlap
    n_SSB_blocks: 3
    final_feats: 64
    ker_ex_numblock: 3

#### path
path:
  pretrain_model_G: ~ #/data/yp/HSI/DBSR-SR-master/experiments/DBSR/DBSRx4_setting1/models/35000_G.pth
  strict_load: true
  resume_state: ~ #/data/yp/HSI/DBSR-SR-master/experiments/DBSR/DBSRx4_setting1/training_state/35000.state

#### training settings: learning rate scheme, loss
train:
  lr_G: !!float 5e-4
  lr_E: !!float 5e-4
  lr_scheme: MultiStepLR # CosineAnnealingLR_Restart
  beta1: 0.9 #
  beta2: 0.99
  niter: 50000  # 100000
  warmup_iter: -1  #
  lr_steps: [10000,20000,30000,35000,40000,45000,50000]
  lr_gamma: 0.5
  eta_min: !!float 1e-7  
  pixel_criterion: myloss #l_pix.type: l1
  pixel_weight: 1.0

  manual_seed: 0
  val_freq: !!float 2500

#### logger
logger:
  print_freq: 20
  save_checkpoint_freq: !!float 2500
