#### general settings
name: DBSRx8_setting1
use_tb_logger: true
model: blind
distortion: sr
scale: 8
gpu_ids: [3,4]
pca_matrix_path: ../../../pca_matrix/DBSR/pca_matrix.pth

degradation:
  random_kernel: True
  ksize: 21
  code_length: 10
  sig_min: 0.2
  sig_max: 4.0
  rate_iso: 1.0
  random_disturb: false

#### datasets
datasets:
  train:
    name: Chikusei_4blur1
    mode: GT
    #dataroot_GT: /data/yp/HSI/Data/Cave/Train/4_blur/
    #dataroot_GT: /data/yp/HSI/Data/Harvard/Train/4_blur/
    dataroot_GT: /home/lwd/Dataset_yp/HSISR/Chikusei/8/Chikusei_x8_blur/trains/


    use_shuffle: true
    n_workers: 8  # per GPU
    batch_size: 32
    GT_size: 128
    LR_size: 16
    use_flip: true
    use_rot: true
    color: RGB
  val:
    name: Chikusei_8blur1
    mode: LQGT
    #dataroot_LQGT: /data/yp/HSI/Data/Cave/Test/4_blur/
    #dataroot_LQGT: /data/yp/HSI/Data/Harvard/Test/4_blur/
    dataroot_LQGT: /home/lwd/Dataset_yp/HSISR/Chikusei/8/Chikusei_x8_blur/tests/

#### network structures
network_G:
  which_model_G: DBSR
  setting:
    nf: 64
    nb: 5 #10
    ng: 3  #5
    input_para: 256
    kernel_size: 21
    in_nc: 128 #
    n_subs: 8 # the sub band in each group
    n_ovls: 2 # the number of overlap
    n_SSB_blocks: 3
    final_feats: 128
    ker_ex_numblock: 3

#### path
path:
  pretrain_model_G: /home/lwd/code_yp/DBSR-SR/experiments/DBSR/DBSRx4_setting1/models/5000_G.pth
  strict_load: true
  resume_state: /home/lwd/code_yp/DBSR-SR/experiments/DBSR/DBSRx4_setting1/training_state/5000.state

#### training settings: learning rate scheme, loss
train:
  lr_G: !!float 4e-4
  lr_E: !!float 4e-4
  lr_scheme: MultiStepLR # 
  beta1: 0.9 #
  beta2: 0.99
  niter: 40000  # 500000
  warmup_iter: -1  # no warm up
  lr_steps: [5000,10000,15000,20000,25000,30000]

  lr_gamma: 0.8
  eta_min: !!float 1e-7 

  pixel_criterion: myloss #l_pix.type: l1   
  pixel_weight: 1.0

  manual_seed: 0
  val_freq: !!float 1000

#### logger
logger:
  print_freq: 20
  save_checkpoint_freq: !!float 1000
